[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camt053_parser = { path = "../camt053_parser" }
thiserror = "1.0.44"
ynab_csv = { path = "../ynab_csv" }
